export interface Stat {
    stat: {
        atBats?: number,
        avg?: string,
        baseOnBalls?: number,
        caughtStealing?: number,
        doubles?: number,
        groundOuts?: number,
        groundOutsToAirouts?: string,
        hitByPitch?: number,
        hits?: number,
        homeRuns?: number,
        intentionalWalks?: number,
        leftOnBase?: number,
        obp?: string,
        ops?: string,
        plateAppearances?: number,
        rbi?: number,
        runs?: number,
        sacBunts?: number,
        sacFlies?: number,
        slg?: string,
        stolenBasePercentage?: string,
        stolenBases?: number,
        strikeOuts?: number,
        totalBases?: number,
        triples?: number,
 }
}
